language: node_js
node_js:
  - "stable"

branches:
  only:
    - development

script:
- yarn install
- yarn test
- yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
