language: node_js
node_js:
  - "10.15.3"

before_install:
  - npm i -g npm@6.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - development

script:
  - npm install --prefix client
  - npm test --prefix client

deploy:
  provider: heroku
  app: "add-a-thing"
  api_key:
    secure: "$HEROKU_API"
