language: node_js
node_js:
  - "stable"

branches:
  only:
    - development

script:
  - npm install
  - npm test
  - npm build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
