language: node_js
node_js:
  - "stable"

before_install:
  - npm i -g npm@6.1.0
  - npm install grpc@1.20.2

cache:
  directories:
    - node_modules

branches:
  only:
    - development

script:
  - npm install
  - npm build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
