language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - development

script:
  - yarn install
  - yarn test
  - yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
