language: node_js
node_js:
  - "10.3.0"

before_install:
  - npm i -g npm@6.9.0
  - npm i -g firebase-tools

cache:
  directories:
    - node_modules

branches:
  only:
    - development

script:
  - npm install --prefix client
  - npm test --prefix client
  # - npm run-script build

# after_success:
#   - firebase deploy --token "$FIREBASE_TOKEN"
