const ADD_DASHBOARD = 'ADD_DASHBOARD';
const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
const FETCH_DASHES = 'FETCH_DASHES';
const FETCH_TASKLIST = 'FETCH_TASKLIST';
const TASKLIST_REF = 'TASKLIST_REF';
const FETCH_TASKSTATUS = 'FETCH_TASKSTATUS';
const FETCH_SUBTASKLIST = 'FETCH_SUBTASKLIST';
const SET_SUBTASK_FILTER = 'SET_SUBTASK_FILTER';
const ADD_TASK = 'ADD_TASK';
const FETCH_TASK_DETAILS = 'FETCH_TASK_DETAILS';
const UPDATE_TASK_DETAILS = 'UPDATE_TASK_DETAILS';
const DELETE_TASK_DETAILS = 'DELETE_TASK_DETAILS';


export {
  ADD_DASHBOARD,
  DELETE_DASHBOARD,
  FETCH_DASHES,
  FETCH_TASKLIST,
  TASKLIST_REF,
  FETCH_TASKSTATUS,
  FETCH_SUBTASKLIST,
  SET_SUBTASK_FILTER,
  ADD_TASK,
  FETCH_TASK_DETAILS,
  UPDATE_TASK_DETAILS,
  DELETE_TASK_DETAILS,
};
