const ADD_DASHBOARD = 'ADD_DASHBOARD';
const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
const FETCH_DASHES = 'FETCH_DASHES';
const FETCH_TASKSTATUS = 'FETCH_TASKSTATUS';
const FETCH_SUBTASKLIST = 'FETCH_SUBTASKLIST';

export {
  ADD_DASHBOARD,
  DELETE_DASHBOARD,
  FETCH_DASHES,
  FETCH_TASKSTATUS,
  FETCH_SUBTASKLIST,
};
