const ADD_DASHBOARD = 'ADD_DASHBOARD';
const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
const FETCH_DASHES = 'FETCH_DASHES';
const FETCH_TASKLIST = 'FETCH_TASKLIST';
const FETCH_TASKSTATUS = 'FETCH_TASKSTATUS';
const FETCH_SUBTASKLIST = 'FETCH_SUBTASKLIST';
const SET_SUBTASK_FILTER = 'SET_SUBTASK_FILTER';
const ADD_TASK = 'ADD_TASK';
const FETCH_TASK_DETAILS = 'FETCH_TASK_DETAILS';
const UPDATE_TASK_DETAILS = 'UPDATE_TASK_DETAILS';
const DELETE_TASK_DETAILS = 'DELETE_TASK_DETAILS';
const ADD_SUBTASK = 'ADD_SUBTASK';
const UPDATE_SUBTASK = 'UPDATE_SUBTASK';
const DELETE_SUBTASK = 'DELETE_SUBTASK';
const SET_SORT = 'SET_SORT';
const REGISTER_USER = 'REGISTER_USER';
const LOG_IN_USER = 'LOG_IN_USER';
const LOG_OUT_USER = 'LOG_OUT_USER';
const FETCH_DASHBOARD_NAME_IN_TASKLIST = 'FETCH_DASHBOARD_NAME_IN_TASKLIST';
const ERROR_HANDLER = 'ERROR_HANDLER';
const SET_CHAT_VISIBILITY = 'SET_CHAT_VISIBILITY';
const ADD_MESSAGE = 'ADD_MESSAGE';
const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export {
  DELETE_SUBTASK,
  UPDATE_SUBTASK,
  ADD_DASHBOARD,
  DELETE_DASHBOARD,
  FETCH_DASHES,
  FETCH_TASKLIST,
  FETCH_TASKSTATUS,
  FETCH_SUBTASKLIST,
  SET_SUBTASK_FILTER,
  ADD_TASK,
  FETCH_TASK_DETAILS,
  UPDATE_TASK_DETAILS,
  DELETE_TASK_DETAILS,
  ADD_SUBTASK,
  SET_SORT,
  REGISTER_USER,
  LOG_IN_USER,
  LOG_OUT_USER,
  FETCH_DASHBOARD_NAME_IN_TASKLIST,
  ERROR_HANDLER,
  SET_CHAT_VISIBILITY,
  ADD_MESSAGE,
  CLEAR_MESSAGES,
};
